name:                jsem
version:             0.1.3
synopsis:            Japanese (FraCaS-style) semantic test suit and Haskell tools
description:         Please see the README on Github at <https://github.com/DaisukeBekki/JSeM#readme>
author:              Daisuke Bekki and Ai Kawazoe
maintainer:          bekki@is.ocha.ac.jp
copyright:           Daisuke Bekki and Ai Kawazoe
license:             AllRightsReserved
github:              DaisukeBekki/JSeM
ghc-options:         -Wall
extra-source-files:
  - README.md
  - ChangeLog.md
  - data/jsem.xsl
  - data/jsem.dtd
dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2
  - bytestring >= 0.10
  - filepath >= 1.4
  - directory >= 1.2
  - shelly >= 1.4
  - containers >= 0.4
  - xml-conduit >= 1.3
  - parsec >= 3.1
library:
  source-dirs: src
  default-extensions: OverloadedStrings
  exposed-modules:
    - JSeM.TSV2XML
    - JSeM.Cmd
    - JSeM.XML
    - JSeM.Dataset
  other-modules: []
executables:
  update:
    main:         update.hs
    source-dirs:  app
    ghc-options:  ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
    dependencies: jsem
  restore:
    main:         restore.hs
    source-dirs:  app
    ghc-options:  ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
    dependencies: jsem
  check:
    main:         check.hs
    source-dirs:  app
    ghc-options:  ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
    dependencies: jsem
  show-stat:
    main:         show-stat.hs
    source-dirs:  app
    ghc-options:  ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
    dependencies: jsem
  tsv2xml:
    main:         tsv2xml.hs
    source-dirs:  app
    ghc-options:  ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
    dependencies: jsem
  xml2tsv:
    main:         xml2tsv.hs
    source-dirs:  app
    ghc-options:  ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
    dependencies: jsem
  xml2txt:
    main:         xml2txt.hs
    source-dirs:  app
    ghc-options:  ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
    dependencies: jsem
