resolver: lts-18.28

flags: {}

system-ghc: true

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true
